### ISSUE TITLE
Cannot start up docker-compose

### ISSUE THREAD

**Issue by nathanloyer** [vrudikov/typescript-rest-boilerplate#13] opened 2019-07-22 14:52 UTC
I just tried checking out master and starting this project up using the commands in the readme. 

```
npm install
./build.sh
docker-compose up
```

And I got an error from the api server:

```typescript-rest-boilerplate_1  | Error starting server: Unexpected token export```

I didn't make any local modifications or anything so I'm not sure why it wouldn't work. I'm on a mac with macos v10.12.6, npm v5.10.0, node v8.12.0, docker-compose v1.23.2, docker v18.09.2.

Is this something in my environment that is messed up? I can give more information if needed.

**Comment by vrudikov** [comment] 2019-07-23 11:06
Let me check

**Comment by vrudikov** [comment] 2019-07-23 12:45
yep. reproduced. want to try to fix it today-tomorrow

**Comment by marekkrivan** [comment] 2019-07-30 07:34
Hi, I have the same problem. Yesterday I downloaded this boilerplate a can not start the server via docker. When will be fixed this problem?

**Comment by vrudikov** [comment] 2019-07-30 15:12
Fix in progress

**Comment by vrudikov** [comment] 2019-07-30 16:12
The issue is fixed. Please check updated readme

**Closed as completed** 2019-07-30 16:12 UTC
